version: 2
workflows:
  version: 2
  tests:
    jobs:
      - unit
jobs:
  unit:
    docker:
      - image: golang:1.10
    environment:
      GOPATH: /go
    working_directory: /go/src/github.com/googleapis/gapic-showcase
    steps:
      - checkout
      - run:
          name: Check formatting
          command: "! gofmt -l ./ 2>&1 | read"
      - run:
          name: Lint code
          command: "! go lint ./... 2>&1 | read"
      - run:
          name: Examine and report suspicious constructs
          command: "! go tool vet ./ 2>&1 | read"
      - run:
          name: Install dependencies
          command: go get -v -t -d ./server/... && go get -v -t -d ./cmd/...
      - run:
          name: Run tests
          command: go test ./... -coverprofile=coverage.txt -covermode=atomic
      - run:
          name: Submit coverage data to codecov.
          command: bash <(curl -s https://codecov.io/bash)
          when: always
